////////////////////////////////////////////
////////   cropAndFreshProducesData

export const cropAndFreshPDP = [
  {
    id: "fruit-01",
    productName: "Organic Gala Apples",
    images: ["/products/agriProducts/CropsAndFreshProduces/redApple.jpg"],
    description:
      "Freshly picked organic Gala apples, rich in flavor and nutrients. Ideal for snacking or baking.",
    specs: { origin: "Local Farms", size: "Medium", organic: true },
    rating: 4,
    reviews: [
      {
        name: "Ali",
        comment: "Crisp and delicious!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/10.jpg",
        reviewDate: "2025-06-01",
        likesCount: 15,
      },
      {
        name: "Sara",
        comment: "Perfect for my fruit salad.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/20.jpg",
        reviewDate: "2025-06-02",
        likesCount: 19,
      },
    ],
    stock: 34,
    discountPrice: "52",
    originalPrice: "60",
    category: "Fruits",
  },
  {
    id: "fruit-02",
    productName: "Bananas",
    images: ["/products/agriProducts/CropsAndFreshProduces/bananas.jpg"],
    description:
      "Naturally sweet and full of potassium, our bananas are ideal for a healthy snack or smoothie.",
    specs: { origin: "Upper Egypt", ripeness: "Medium", size: "Large" },
    rating: 3,
    reviews: [
      {
        name: "Khaled",
        comment: "Nice and soft.",
        rating: 3,
        image: "https://randomuser.me/api/portraits/men/33.jpg",
        reviewDate: "2025-06-01",
        likesCount: 7,
      },
      {
        name: "Noura",
        comment: "Good for smoothies.",
        rating: 3,
        image: "https://randomuser.me/api/portraits/women/27.jpg",
        reviewDate: "2025-06-04",
        likesCount: 12,
      },
    ],
    stock: 40,
    discountPrice: "28",
    originalPrice: "32",
    category: "Fruits",
  },
  {
    id: "fruit-03",
    productName: "Grapes",
    images: ["/products/agriProducts/CropsAndFreshProduces/grapes.jpg"],
    description:
      "Sweet and juicy grapes perfect for snacking or making juice. Grown without synthetic pesticides.",
    specs: { color: "Red", seedless: true, weight: "1kg" },
    rating: 5,
    reviews: [
      {
        name: "Samir",
        comment: "Very sweet and fresh.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/22.jpg",
        reviewDate: "2025-06-03",
        likesCount: 17,
      },
      {
        name: "Fatma",
        comment: "Kids love them!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/48.jpg",
        reviewDate: "2025-06-06",
        likesCount: 22,
      },
    ],
    stock: 25,
    discountPrice: "60",
    originalPrice: "65",
    category: "Fruits",
  },
  {
    id: "fruit-04",
    productName: "Green Apples",
    images: ["/products/agriProducts/CropsAndFreshProduces/greenApple.jpg"],
    description:
      "Tangy and crisp green apples, perfect for juicing or baking pies.",
    specs: { taste: "Tart", skin: "Shiny", size: "Medium" },
    rating: 2,
    reviews: [
      {
        name: "Mona",
        comment: "A bit too sour for me.",
        rating: 2,
        image: "https://randomuser.me/api/portraits/women/34.jpg",
        reviewDate: "2025-06-05",
        likesCount: 5,
      },
      {
        name: "Ahmed",
        comment: "Exactly what I wanted.",
        rating: 3,
        image: "https://randomuser.me/api/portraits/men/13.jpg",
        reviewDate: "2025-06-07",
        likesCount: 9,
      },
    ],
    stock: 20,
    discountPrice: "45",
    originalPrice: "50",
    category: "Fruits",
  },
  {
    id: "fruit-05",
    productName: "Pears",
    images: ["/products/agriProducts/CropsAndFreshProduces/pears.jpg"],
    description:
      "Juicy and mellow pears perfect for snacking and desserts. Rich in fiber and vitamin C.",
    specs: { origin: "Delta", type: "Bartlett", size: "Large" },
    rating: 4,
    reviews: [
      {
        name: "Omar",
        comment: "Fresh and tasty pears.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/44.jpg",
        reviewDate: "2025-06-09",
        likesCount: 14,
      },
      {
        name: "Laila",
        comment: "Great for baking pies.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/56.jpg",
        reviewDate: "2025-06-10",
        likesCount: 18,
      },
    ],
    stock: 30,
    discountPrice: "68",
    originalPrice: "75",
    category: "Fruits",
  },
  {
    id: "fruit-06",
    productName: "Fig",
    images: ["/products/agriProducts/CropsAndFreshProduces/fig.jpg"],
    description:
      "Sweet seasonal figs loaded with antioxidants and dietary fiber.",
    specs: { variety: "Black Mission", texture: "Soft", organic: false },
    rating: 3,
    reviews: [
      {
        name: "Nada",
        comment: "Very soft and tasty.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/38.jpg",
        reviewDate: "2025-06-11",
        likesCount: 13,
      },
      {
        name: "Hussein",
        comment: "A bit overripe.",
        rating: 2,
        image: "https://randomuser.me/api/portraits/men/39.jpg",
        reviewDate: "2025-06-12",
        likesCount: 9,
      },
    ],
    stock: 16,
    discountPrice: "24",
    originalPrice: "28",
    category: "Fruits",
  },
  {
    id: "fruit-07",
    productName: "Strawberry",
    images: ["/products/agriProducts/CropsAndFreshProduces/strawberry.jpg"],
    description:
      "*Note: Product image is strawberry. Verify name.* Likely to be fresh strawberries – juicy and sweet.",
    specs: { origin: "Coastal", season: "Spring", type: "Fresh berries" },
    rating: 3,
    reviews: [
      {
        name: "Ali",
        comment: "Fresh but mislabeled?",
        rating: 3,
        image: "https://randomuser.me/api/portraits/men/20.jpg",
        reviewDate: "2025-06-14",
        likesCount: 6,
      },
    ],
    stock: 22,
    discountPrice: "30",
    originalPrice: "35",
    category: "Fruits",
  },
  {
    id: "vege-01",
    productName: "Tomato",
    images: ["/products/agriProducts/CropsAndFreshProduces/tomato1.jpg"],
    description:
      "Juicy and ripe tomatoes perfect for salads, sauces, and everyday cooking.",
    specs: { origin: "Local farms", type: "Roma", shelfLife: "7 days" },
    rating: 4,
    reviews: [
      {
        name: "Alaa",
        comment: "Very fresh and tasty.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/33.jpg",
        reviewDate: "2025-06-20",
        likesCount: 16,
      },
      {
        name: "Sara",
        comment: "Nice flavor and good size.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/36.jpg",
        reviewDate: "2025-06-21",
        likesCount: 12,
      },
    ],
    stock: 24,
    discountPrice: "36",
    originalPrice: "42",
    category: "Vegetables",
  },
  {
    id: "vege-02",
    productName: "onion",
    images: ["/products/agriProducts/CropsAndFreshProduces/onion1.jpg"],
    description:
      "Aromatic and versatile onions great for cooking and garnishing.",
    specs: {
      origin: "Delta region",
      type: "Yellow onion",
      shelfLife: "30 days",
    },
    rating: 4,
    reviews: [
      {
        name: "Mahmoud",
        comment: "Good quality, arrived fresh.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/40.jpg",
        reviewDate: "2025-06-20",
        likesCount: 10,
      },
      {
        name: "Nora",
        comment: "Perfect for cooking.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/41.jpg",
        reviewDate: "2025-06-22",
        likesCount: 13,
      },
    ],
    stock: 35,
    discountPrice: "30",
    originalPrice: "35",
    category: "Vegetables",
  },
  {
    id: "vege-03",
    productName: "Potato",
    images: ["/products/agriProducts/CropsAndFreshProduces/potato1.jpg"],
    description: "Staple food with a rich source of carbohydrates and fiber.",
    specs: { origin: "Upper Egypt", type: "Spunta", shelfLife: "25 days" },
    rating: 3,
    reviews: [
      {
        name: "Ali",
        comment: "Fair size and taste.",
        rating: 3,
        image: "https://randomuser.me/api/portraits/men/50.jpg",
        reviewDate: "2025-06-19",
        likesCount: 9,
      },
      {
        name: "Mona",
        comment: "Good for frying and boiling.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/49.jpg",
        reviewDate: "2025-06-20",
        likesCount: 14,
      },
    ],
    stock: 40,
    discountPrice: "17",
    originalPrice: "20",
    category: "Vegetables",
  },
  {
    id: "vege-04",
    productName: "Carrot",
    images: ["/products/agriProducts/CropsAndFreshProduces/carrot1.jpg"],
    description: "Crunchy, sweet carrots full of vitamins and antioxidants.",
    specs: { origin: "Ismailia", type: "Nantes", shelfLife: "14 days" },
    rating: 5,
    reviews: [
      {
        name: "Youssef",
        comment: "Very sweet and crisp.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/60.jpg",
        reviewDate: "2025-06-23",
        likesCount: 18,
      },
      {
        name: "Lina",
        comment: "Kids love them.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/59.jpg",
        reviewDate: "2025-06-24",
        likesCount: 22,
      },
    ],
    stock: 20,
    discountPrice: "48",
    originalPrice: "55",
    category: "Vegetables",
  },
  {
    id: "vege-05",
    productName: "Cucumbers",
    images: [
      "/products/agriProducts/CropsAndFreshProduces/cucumbers.jpg",
      "/products/agriProducts/CropsAndFreshProduces/cucumbers.jpg",
      "/products/agriProducts/CropsAndFreshProduces/cucumbers.jpg",
      "/products/agriProducts/CropsAndFreshProduces/cucumbers.jpg",
      "/products/agriProducts/CropsAndFreshProduces/cucumbers.jpg",
    ],
    description: "Fresh and crisp cucumbers ideal for salads and hydration.",
    specs: { origin: "Local Farms", size: "Medium", freshness: "High" },
    rating: 4,
    reviews: [
      {
        name: "Mona",
        comment: "Very fresh and crunchy!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/12.jpg",
        reviewDate: "2025-06-10",
        likesCount: 10,
      },
      {
        name: "Ali",
        comment: "Best cucumbers I’ve had this season.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/35.jpg",
        reviewDate: "2025-06-11",
        likesCount: 14,
      },
      {
        name: "Yara",
        comment: "Cool and refreshing, great with yogurt.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/52.jpg",
        reviewDate: "2025-06-12",
        likesCount: 13,
      },
    ],
    stock: 22,
    discountPrice: "27",
    originalPrice: "30",
    category: "Vegetables",
  },

  {
    id: "vege-06",
    productName: "Cauliflower",
    images: [
      "/products/agriProducts/CropsAndFreshProduces/cauliflower.jpg",
      "/products/agriProducts/CropsAndFreshProduces/cauliflower.jpg",
      "/products/agriProducts/CropsAndFreshProduces/cauliflower.jpg",
      "/products/agriProducts/CropsAndFreshProduces/cauliflower.jpg",
      "/products/agriProducts/CropsAndFreshProduces/cauliflower.jpg",
    ],
    description:
      "Nutritious and versatile white cauliflower, great for roasting or steaming.",
    specs: { size: "Large Head", freshness: "High", shelfLife: "4 days" },
    rating: 4,
    reviews: [
      {
        name: "Hassan",
        comment: "Big head and really fresh.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/44.jpg",
        reviewDate: "2025-06-13",
        likesCount: 11,
      },
      {
        name: "Salma",
        comment: "Perfect for my veggie dishes.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/41.jpg",
        reviewDate: "2025-06-14",
        likesCount: 15,
      },
      {
        name: "Omar",
        comment: "Clean and tastes great!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/25.jpg",
        reviewDate: "2025-06-15",
        likesCount: 12,
      },
    ],
    stock: 16,
    discountPrice: "30",
    originalPrice: "35",
    category: "Vegetables",
  },
  {
    id: "vege-07",
    productName: "Corn",
    images: [
      "/products/agriProducts/CropsAndFreshProduces/corn.jpg",
      "/products/agriProducts/CropsAndFreshProduces/corn.jpg",
      "/products/agriProducts/CropsAndFreshProduces/corn.jpg",
      "/products/agriProducts/CropsAndFreshProduces/corn.jpg",
      "/products/agriProducts/CropsAndFreshProduces/corn.jpg",
    ],
    description:
      "Golden yellow corn, sweet and juicy – perfect for grilling or boiling.",
    specs: { kernelType: "Sweet", packaging: "Loose", origin: "Nile Valley" },
    rating: 4,
    reviews: [
      {
        name: "Noor",
        comment: "Juicy and super sweet.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/60.jpg",
        reviewDate: "2025-06-16",
        likesCount: 13,
      },
      {
        name: "Ibrahim",
        comment: "Great flavor when grilled.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/37.jpg",
        reviewDate: "2025-06-17",
        likesCount: 15,
      },
      {
        name: "Rania",
        comment: "Loved it! Will buy again.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/23.jpg",
        reviewDate: "2025-06-18",
        likesCount: 17,
      },
    ],
    stock: 18,
    discountPrice: "27",
    originalPrice: "30",
    category: "Vegetables",
  },

  {
    id: "vege-08",
    productName: "Chili Peppers",
    images: [
      "/products/agriProducts/CropsAndFreshProduces/chiliPeppers.jpg",
      "/products/agriProducts/CropsAndFreshProduces/chiliPeppers.jpg",
      "/products/agriProducts/CropsAndFreshProduces/chiliPeppers.jpg",
      "/products/agriProducts/CropsAndFreshProduces/chiliPeppers.jpg",
      "/products/agriProducts/CropsAndFreshProduces/chiliPeppers.jpg",
    ],
    description: "Spicy red chili peppers for cooking and pickling.",
    specs: { spiceLevel: "High", color: "Red", shelfLife: "5 days" },
    rating: 4,
    reviews: [
      {
        name: "Ahmed",
        comment: "Hot and fresh, just like I love it!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/31.jpg",
        reviewDate: "2025-06-19",
        likesCount: 14,
      },
      {
        name: "Dina",
        comment: "Adds great kick to food.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/34.jpg",
        reviewDate: "2025-06-20",
        likesCount: 11,
      },
      {
        name: "Mahmoud",
        comment: "Strong flavor, very spicy!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/29.jpg",
        reviewDate: "2025-06-21",
        likesCount: 12,
      },
    ],
    stock: 21,
    discountPrice: "28",
    originalPrice: "32",
    category: "Vegetables",
  },
  {
    id: "vege-09",
    productName: "Lemon",
    images: [
      "/products/agriProducts/CropsAndFreshProduces/lemon.jpg",
      "/products/agriProducts/CropsAndFreshProduces/lemon.jpg",
      "/products/agriProducts/CropsAndFreshProduces/lemon.jpg",
      "/products/agriProducts/CropsAndFreshProduces/lemon.jpg",
      "/products/agriProducts/CropsAndFreshProduces/lemon.jpg",
    ],
    description:
      "Fresh yellow lemons rich in vitamin C, perfect for seasoning and beverages.",
    specs: { size: "Medium", acidity: "High", freshness: "Excellent" },
    rating: 4,
    reviews: [
      {
        name: "Nada",
        comment: "Perfect for lemonade and detox drinks.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/15.jpg",
        reviewDate: "2025-06-20",
        likesCount: 12,
      },
      {
        name: "Mostafa",
        comment: "Very juicy and fresh.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/21.jpg",
        reviewDate: "2025-06-21",
        likesCount: 10,
      },
      {
        name: "Rania",
        comment: "Love using it in cooking and tea!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/38.jpg",
        reviewDate: "2025-06-22",
        likesCount: 15,
      },
    ],
    stock: 19,
    discountPrice: "26",
    originalPrice: "30",
    category: "Fruit",
  },

  {
    id: "vege-10",
    productName: "Peas",
    images: [
      "/products/agriProducts/CropsAndFreshProduces/peas.jpg",
      "/products/agriProducts/CropsAndFreshProduces/peas.jpg",
      "/products/agriProducts/CropsAndFreshProduces/peas.jpg",
      "/products/agriProducts/CropsAndFreshProduces/peas.jpg",
      "/products/agriProducts/CropsAndFreshProduces/peas.jpg",
    ],
    description: "Sweet green peas, perfect for soups, stews, and rice dishes.",
    specs: { podType: "Green", taste: "Sweet", freshness: "High" },
    rating: 4,
    reviews: [
      {
        name: "Khaled",
        comment: "Sweet and clean, great with rice.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/32.jpg",
        reviewDate: "2025-06-21",
        likesCount: 13,
      },
      {
        name: "Salma",
        comment: "Perfect for pea soup.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/50.jpg",
        reviewDate: "2025-06-22",
        likesCount: 12,
      },
      {
        name: "Hassan",
        comment: "Really fresh and tasty.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/26.jpg",
        reviewDate: "2025-06-23",
        likesCount: 14,
      },
    ],
    stock: 20,
    discountPrice: "30",
    originalPrice: "34",
    category: "Vegetable",
  },
];

////////////////////////////////////////////
////////  Dairy & livestock

export const dairyAndLivestockPDP = [
  {
    id: "animal-01",
    productName: "Fresh Chicken Eggs (30 pcs)",
    images: [
      "/products/agriProducts/DairyAndLivestock/egg3.jpg",
      "/products/agriProducts/DairyAndLivestock/egg3.jpg",
      "/products/agriProducts/DairyAndLivestock/egg3.jpg",
    ],
    description:
      "Farm-fresh chicken eggs, unprocessed and packed with nutrition. Ideal for daily meals and baking.",
    specs: {
      packSize: "30 eggs",
      type: "Chicken Egg",
      source: "Free-range hens",
    },
    rating: 5,
    reviews: [
      {
        name: "Amira",
        comment: "Always fresh and perfectly sized.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/12.jpg",
        reviewDate: "2025-06-08",
        likesCount: 14,
      },
      {
        name: "Ziad",
        comment: "Great value and taste.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/15.jpg",
        reviewDate: "2025-06-09",
        likesCount: 11,
      },
    ],
    stock: 34,
    discountPrice: "45",
    originalPrice: "50",
    category: "Dairy",
  },
  {
    id: "animal-02",
    productName: "Raw Cow Milk (1L)",
    images: [
      "/products/agriProducts/DairyAndLivestock/milk2.jpg",
      "/products/agriProducts/DairyAndLivestock/milk2.jpg",
      "/products/agriProducts/DairyAndLivestock/milk2.jpg",
    ],
    description:
      "Unprocessed cow milk directly sourced from local farms. Rich in nutrients and ideal for boiling or cooking.",
    specs: {
      volume: "1 liter",
      source: "Grass-fed cows",
      packaging: "Reusable bottle",
    },
    rating: 5,
    reviews: [
      {
        name: "Karim",
        comment: "Rich and creamy, exactly how milk should be.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/26.jpg",
        reviewDate: "2025-06-10",
        likesCount: 18,
      },
      {
        name: "Mona",
        comment: "So much better than store milk.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/37.jpg",
        reviewDate: "2025-06-11",
        likesCount: 16,
      },
    ],
    stock: 21,
    discountPrice: "25",
    originalPrice: "28",
    category: "Dairy",
  },

  {
    id: "animal-03",
    productName: "Beef Steak (Boneless)",
    images: [
      "/products/agriProducts/DairyAndLivestock/sirloinSteak.jpg",
      "/products/agriProducts/DairyAndLivestock/sirloinSteak.jpg",
      "/products/agriProducts/DairyAndLivestock/sirloinSteak.jpg",
    ],
    description:
      "Premium boneless beef steak, tender and flavorful. Ideal for grilling or pan-searing.",
    specs: {
      type: "Boneless",
      origin: "Local pasture-raised cattle",
      cut: "Sirloin",
    },
    rating: 5,
    reviews: [
      {
        name: "Omar",
        comment: "Excellent cut, juicy and fresh.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/21.jpg",
        reviewDate: "2025-06-09",
        likesCount: 20,
      },
      {
        name: "Sara",
        comment: "Grills beautifully. Highly recommend.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/28.jpg",
        reviewDate: "2025-06-10",
        likesCount: 18,
      },
    ],
    stock: 12,
    discountPrice: "200",
    originalPrice: "220",
    category: "Meat",
  },
  {
    id: "animal-04",
    productName: "Feta Cheese",
    images: [
      "/products/agriProducts/DairyAndLivestock/fetaCheese.jpg",
      "/products/agriProducts/DairyAndLivestock/fetaCheese.jpg",
      "/products/agriProducts/DairyAndLivestock/fetaCheese.jpg",
    ],
    description:
      "Creamy and salty feta cheese made from fresh cow's milk. Perfect for salads and sandwiches.",
    specs: {
      weight: "250g",
      texture: "Crumbly",
      origin: "Local dairy farms",
    },
    rating: 5,
    reviews: [
      {
        name: "Layla",
        comment: "Delicious and authentic feta taste.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/11.jpg",
        reviewDate: "2025-06-12",
        likesCount: 22,
      },
      {
        name: "Hussein",
        comment: "One of the best I’ve tried.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/31.jpg",
        reviewDate: "2025-06-13",
        likesCount: 17,
      },
    ],
    stock: 30,
    discountPrice: "60",
    originalPrice: "65",
    category: "Dairy",
  },

  {
    id: "animal-05",
    productName: "Natural Honey (Pure)",
    images: [
      "/products/agriProducts/DairyAndLivestock/honey.jpg",
      "/products/agriProducts/DairyAndLivestock/honey.jpg",
      "/products/agriProducts/DairyAndLivestock/honey.jpg",
    ],
    description:
      "Pure, unfiltered natural honey with a golden hue and rich floral aroma. Great for health and sweetness.",
    specs: {
      weight: "500g",
      origin: "Mountain bees",
      texture: "Thick & Smooth",
    },
    rating: 5,
    reviews: [
      {
        name: "Amina",
        comment: "So pure and tasty. I use it every morning.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/25.jpg",
        reviewDate: "2025-06-14",
        likesCount: 24,
      },
      {
        name: "Khaled",
        comment: "The flavor is outstanding!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/35.jpg",
        reviewDate: "2025-06-15",
        likesCount: 20,
      },
    ],
    stock: 22,
    discountPrice: "95",
    originalPrice: "105",
    category: "Honey",
  },
  {
    id: "animal-06",
    productName: "Free-Range Chicken (Whole)",
    images: [
      "/products/agriProducts/DairyAndLivestock/rawChicken.webp",
      "/products/agriProducts/DairyAndLivestock/rawChicken.webp",
      "/products/agriProducts/DairyAndLivestock/rawChicken.webp",
    ],
    description:
      "Whole free-range chicken with rich flavor and firm texture. Perfect for roasting or stewing.",
    specs: {
      weight: "Approx. 1.5kg",
      type: "Whole",
      source: "Free-range poultry farm",
    },
    rating: 5,
    reviews: [
      {
        name: "Nour",
        comment: "Juicy and flavorful — I always get this one.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/42.jpg",
        reviewDate: "2025-06-16",
        likesCount: 21,
      },
      {
        name: "Samir",
        comment: "Very fresh and healthy option.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/39.jpg",
        reviewDate: "2025-06-17",
        likesCount: 19,
      },
    ],
    stock: 14,
    discountPrice: "105",
    originalPrice: "115",
    category: "Meat",
  },
  {
    id: "animal-07",
    productName: "Chicken Breasts",
    images: [
      "/products/agriProducts/DairyAndLivestock/chickenBreasts.jpg",
      "/products/agriProducts/DairyAndLivestock/chickenBreasts.jpg",
      "/products/agriProducts/DairyAndLivestock/chickenBreasts.jpg",
    ],
    description:
      "Lean, boneless chicken breasts perfect for grilling, roasting, or slicing into strips.",
    specs: {
      weight: "1kg",
      cut: "Boneless",
      freshness: "Delivered chilled",
    },
    rating: 5,
    reviews: [
      {
        name: "Rasha",
        comment: "Very clean and lean, my go-to protein source.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/36.jpg",
        reviewDate: "2025-06-18",
        likesCount: 25,
      },
      {
        name: "Tamer",
        comment: "Nice texture and fresh smell.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/62.jpg",
        reviewDate: "2025-06-19",
        likesCount: 20,
      },
    ],
    stock: 18,
    discountPrice: "105",
    originalPrice: "115",
    category: "Meat",
  },
  {
    id: "animal-08",
    productName: "Chicken Thighs",
    images: [
      "/products/agriProducts/DairyAndLivestock/chickenThighs.jpg",
      "/products/agriProducts/DairyAndLivestock/chickenThighs.jpg",
      "/products/agriProducts/DairyAndLivestock/chickenThighs.jpg",
    ],
    description:
      "Tender and juicy chicken thighs with skin, great for frying or baking.",
    specs: {
      weight: "1kg",
      cut: "Bone-in",
      origin: "Local farms",
    },
    rating: 5,
    reviews: [
      {
        name: "Aya",
        comment: "So juicy when cooked! Best quality.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/29.jpg",
        reviewDate: "2025-06-18",
        likesCount: 23,
      },
      {
        name: "Mahmoud",
        comment: "Perfect for my stews and BBQ.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/40.jpg",
        reviewDate: "2025-06-19",
        likesCount: 18,
      },
    ],
    stock: 20,
    discountPrice: "100",
    originalPrice: "110",
    category: "Meat",
  },
  {
    id: "animal-09",
    productName: "Beef Mince",
    images: [
      "/products/agriProducts/DairyAndLivestock/beefMince.webp",
      "/products/agriProducts/DairyAndLivestock/beefMince.webp",
      "/products/agriProducts/DairyAndLivestock/beefMince.webp",
    ],
    description:
      "Fresh ground beef with perfect fat balance for making burgers, meatballs, or sauces.",
    specs: {
      weight: "1kg",
      fatContent: "20%",
      freshness: "Same-day packed",
    },
    rating: 5,
    reviews: [
      {
        name: "Hany",
        comment: "Clean grind, no smell, very tasty.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/35.jpg",
        reviewDate: "2025-06-20",
        likesCount: 19,
      },
      {
        name: "Nahla",
        comment: "Perfect texture, makes juicy kofta.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/51.jpg",
        reviewDate: "2025-06-21",
        likesCount: 22,
      },
    ],
    stock: 11,
    discountPrice: "225",
    originalPrice: "240",
    category: "Meat",
  },
  {
    id: "animal-010",
    productName: "Beef Chuck",
    images: [
      "/products/agriProducts/DairyAndLivestock/beefChuck.jpg",
      "/products/agriProducts/DairyAndLivestock/beefChuck.jpg",
      "/products/agriProducts/DairyAndLivestock/beefChuck.jpg",
    ],
    description:
      "Flavorful cut of beef ideal for slow cooking, stews, or shredding for tacos.",
    specs: {
      weight: "1kg",
      cut: "Chuck",
      marbling: "Moderate",
    },
    rating: 5,
    reviews: [
      {
        name: "Fady",
        comment: "Cooked it slowly, came out super tender.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/23.jpg",
        reviewDate: "2025-06-20",
        likesCount: 17,
      },
      {
        name: "Mai",
        comment: "Rich flavor, amazing in stew recipes.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/40.jpg",
        reviewDate: "2025-06-21",
        likesCount: 20,
      },
    ],
    stock: 9,
    discountPrice: "220",
    originalPrice: "235",
    category: "Meat",
  },
  {
    id: "animal-011",
    productName: "Beef Steak Packed",
    images: [
      "/products/agriProducts/DairyAndLivestock/steak1.jpg",
      "/products/agriProducts/DairyAndLivestock/steak1.jpg",
      "/products/agriProducts/DairyAndLivestock/steak1.jpg",
    ],
    description:
      "Premium quality beef steak slices, vacuum-packed to preserve freshness and flavor.",
    specs: {
      weight: "1kg",
      cut: "Steak",
      packaging: "Vacuum sealed",
    },
    rating: 5,
    reviews: [
      {
        name: "Tarek",
        comment: "Very tender and juicy, excellent steak night.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/38.jpg",
        reviewDate: "2025-06-21",
        likesCount: 24,
      },
      {
        name: "Nour",
        comment: "Restaurant quality at home.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/29.jpg",
        reviewDate: "2025-06-22",
        likesCount: 27,
      },
    ],
    stock: 10,
    discountPrice: "215",
    originalPrice: "230",
    category: "Meat",
  },
  {
    id: "animal-012",
    productName: "Butter",
    images: [
      "/products/agriProducts/DairyAndLivestock/butter.jpg",
      "/products/agriProducts/DairyAndLivestock/butter.jpg",
      "/products/agriProducts/DairyAndLivestock/butter.jpg",
    ],
    description:
      "Creamy and rich dairy butter made from natural cow’s milk, perfect for cooking and baking.",
    specs: {
      weight: "1kg",
      fatContent: "82%",
      type: "Unsalted",
    },
    rating: 5,
    reviews: [
      {
        name: "Mariam",
        comment: "Smooth and flavorful — great quality.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/49.jpg",
        reviewDate: "2025-06-23",
        likesCount: 30,
      },
      {
        name: "Kareem",
        comment: "Excellent in baking and frying.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/52.jpg",
        reviewDate: "2025-06-24",
        likesCount: 26,
      },
    ],
    stock: 14,
    discountPrice: "180",
    originalPrice: "200",
    category: "Dairy",
  },
];
