////////////////////////////////////////////
////////   cropAndFreshProducesData

export const cropAndFreshProducesData = [
  {
    id: "fruit-01",
    productName: "Organic Gala Apples",
    productImage: "/products/agriProducts/CropsAndFreshProduces/redApple.jpg",
    price: "60 EGP/kg",
    discountPrice: "52 EGP/kg",
    rating: 4,
    tags: ["Fruit", "Organic", "Fresh", "Popular"],
  },
  {
    id: "fruit-02",
    productName: "Bananas",
    productImage: "/products/agriProducts/CropsAndFreshProduces/bananas.jpg",
    price: "32 EGP/kg",
    discountPrice: "28 EGP/kg",
    rating: 3,
    tags: ["Fruit", "Tropical", "Fresh"],
  },
  {
    id: "fruit-03",
    productName: "Grapes",
    productImage: "/products/agriProducts/CropsAndFreshProduces/grapes.jpg",
    price: "65 EGP/kg",
    discountPrice: "60 EGP/kg",
    rating: 5,
    tags: ["Fruit", "Sweet", "Fresh"],
  },
  {
    id: "fruit-04",
    productName: "Green Apples",
    productImage: "/products/agriProducts/CropsAndFreshProduces/greenApple.jpg",
    price: "50 EGP/kg",
    discountPrice: "45 EGP/kg",
    rating: 2,
    tags: ["Fruit", "Tart", "Fresh"],
  },
  {
    id: "fruit-05",
    productName: "Pears",
    productImage: "/products/agriProducts/CropsAndFreshProduces/pears.jpg",
    price: "75 EGP/kg",
    discountPrice: "68 EGP/kg",
    rating: 4,
    tags: ["Fruit", "Juicy", "Fresh"],
  },
  {
    id: "fruit-06",
    productName: "Fig",
    productImage: "/products/agriProducts/CropsAndFreshProduces/fig.jpg",
    price: "28 EGP/kg",
    discountPrice: "24 EGP/kg",
    rating: 3,
    tags: ["Fruit", "Seasonal", "Sweet"],
  },
  {
    id: "fruit-07",
    productName: "Strawberry",
    productImage: "/products/agriProducts/CropsAndFreshProduces/strawberry.jpg",
    price: "35 EGP/kg",
    discountPrice: "30 EGP/kg",
    rating: 3,
    tags: ["Fruit", "Seasonal", "Fresh"], // name seems off here (image is strawberry)
  },
  {
    id: "vege-01",
    productName: "Tomato",
    productImage: "/products/agriProducts/CropsAndFreshProduces/tomato1.jpg",
    price: "42 EGP/kg",
    discountPrice: "36 EGP/kg",
    rating: 4,
    tags: ["Vegetable", "Essential", "Fresh"],
  },
  {
    id: "vege-02",
    productName: "onion",
    productImage: "/products/agriProducts/CropsAndFreshProduces/onion1.jpg",
    price: "35 EGP/kg",
    discountPrice: "30 EGP/kg",
    rating: 4,
    tags: ["Vegetable", "Aromatic", "Essential"],
  },
  {
    id: "vege-03",
    productName: "Potato",
    productImage: "/products/agriProducts/CropsAndFreshProduces/potato1.jpg",
    price: "20 EGP/kg",
    discountPrice: "17 EGP/kg",
    rating: 3,
    tags: ["Vegetable", "Starchy", "Essential"],
  },
  {
    id: "vege-04",
    productName: "Carrot",
    productImage: "/products/agriProducts/CropsAndFreshProduces/carrot1.jpg",
    price: "55 EGP/kg",
    discountPrice: "48 EGP/kg",
    rating: 5,
    tags: ["Vegetable", "Root", "Sweet"],
  },
  {
    id: "vege-05",
    productName: "Cucumbers",
    productImage: "/products/agriProducts/CropsAndFreshProduces/cucumbers.jpg",
    price: "30 EGP/kg",
    discountPrice: "27 EGP/kg",
    rating: 4,
    tags: ["Vegetable", "Cool", "Hydrating"],
  },
  {
    id: "vege-06",
    productName: "Cauliflower",
    productImage:
      "/products/agriProducts/CropsAndFreshProduces/cauliflower.jpg",
    price: "35 EGP/kg",
    discountPrice: "30 EGP/kg",
    rating: 4,
    tags: ["Vegetable", "Cruciferous", "White"],
  },
  {
    id: "vege-07",
    productName: "Corn",
    productImage: "/products/agriProducts/CropsAndFreshProduces/corn.jpg",
    price: "30 EGP/kg",
    discountPrice: "27 EGP/kg",
    rating: 4,
    tags: ["Vegetable", "Grain", "Sweet"],
  },
  {
    id: "vege-08",
    productName: "Chili Peppers",
    productImage:
      "/products/agriProducts/CropsAndFreshProduces/chiliPeppers.jpg",
    price: "32 EGP/kg",
    discountPrice: "28 EGP/kg",
    rating: 4,
    tags: ["Vegetable", "Spicy", "Hot"],
  },
  {
    id: "vege-09",
    productName: "Lemon",
    productImage: "/products/agriProducts/CropsAndFreshProduces/lemon.jpg",
    price: "30 EGP/kg",
    discountPrice: "26 EGP/kg",
    rating: 4,
    tags: ["Fruit", "Citrus", "Sour"],
  },
  {
    id: "vege-10",
    productName: "Peas",
    productImage: "/products/agriProducts/CropsAndFreshProduces/peas.jpg",
    price: "34 EGP/kg",
    discountPrice: "30 EGP/kg",
    rating: 4,
    tags: ["Vegetable", "Legume", "Green"],
  },
];

////////////////////////////////////////////
////////  Dairy & livestock

export const dairyAndLivestockProducts = [
  {
    id: "animal-01",
    productName: "Fresh Chicken Eggs (30 pcs)",
    productImage: "/products/agriProducts/DairyAndLivestock/egg3.jpg",
    price: "50 EGP/pack",
    discountPrice: "45 EGP/pack",
    rating: 4.8,
    tags: ["Dairy", "Eggs", "Poultry", "Essential"],
  },
  {
    id: "animal-02",
    productName: "Raw Cow Milk (1L)",
    productImage: "/products/agriProducts/DairyAndLivestock/milk2.jpg",
    price: "28 EGP/liter",
    discountPrice: "25 EGP/liter",
    rating: 4.7,
    tags: ["Dairy", "Milk", "Fresh", "Natural"],
  },
  {
    id: "animal-03",
    productName: "Beef Steak (Boneless)",
    productImage: "/products/agriProducts/DairyAndLivestock/sirloinSteak.jpg",
    price: "220 EGP/kg",
    discountPrice: "200 EGP/kg",
    rating: 4.6,
    tags: ["Meat", "Beef", "Boneless", "Premium"],
  },
  {
    id: "animal-04",
    productName: "Feta Cheese",
    productImage: "/products/agriProducts/DairyAndLivestock/fetaCheese.jpg",
    price: "65 EGP/250g",
    discountPrice: "60 EGP/250g",
    rating: 4.9,
    tags: ["Dairy", "Cheese", "Fresh", "Salty"],
  },
  {
    id: "animal-05",
    productName: "Natural Honey (Pure)",
    productImage: "/products/agriProducts/DairyAndLivestock/honey.jpg",
    price: "105 EGP/jar",
    discountPrice: "95 EGP/jar",
    rating: 5.0,
    tags: ["Honey", "Natural", "Pure", "Sweet"],
  },
  {
    id: "animal-06",
    productName: "Free-Range Chicken (Whole)",
    productImage: "/products/agriProducts/DairyAndLivestock/rawChicken.webp",
    price: "115 EGP/kg",
    discountPrice: "105 EGP/kg",
    rating: 4.6,
    tags: ["Meat", "Poultry", "Whole", "Fresh"],
  },
  {
    id: "animal-07",
    productName: "Chicken Breasts",
    productImage: "/products/agriProducts/DairyAndLivestock/chickenBreasts.jpg",
    price: "115 EGP/kg",
    discountPrice: "105 EGP/kg",
    rating: 4.6,
    tags: ["Meat", "Poultry", "Lean", "Fresh"],
  },
  {
    id: "animal-08",
    productName: "Chicken Thighs",
    productImage: "/products/agriProducts/DairyAndLivestock/chickenThighs.jpg",
    price: "110 EGP/kg",
    discountPrice: "100 EGP/kg",
    rating: 4.6,
    tags: ["Meat", "Poultry", "Juicy", "Cut"],
  },
  {
    id: "animal-09",
    productName: "Beef Mince",
    productImage: "/products/agriProducts/DairyAndLivestock/beefMince.webp",
    price: "240 EGP/kg",
    discountPrice: "225 EGP/kg",
    rating: 4.6,
    tags: ["Meat", "Beef", "Ground", "Cooking"],
  },
  {
    id: "animal-010",
    productName: "Beef Chuck",
    productImage: "/products/agriProducts/DairyAndLivestock/beefChuck.jpg",
    price: "235 EGP/kg",
    discountPrice: "220 EGP/kg",
    rating: 4.6,
    tags: ["Meat", "Beef", "Cut", "Stew"],
  },
  {
    id: "animal-011",
    productName: "Beef Steak Packed",
    productImage: "/products/agriProducts/DairyAndLivestock/steak1.jpg",
    price: "230 EGP/kg",
    discountPrice: "215 EGP/kg",
    rating: 4.6,
    tags: ["Meat", "Beef", "Packed", "Premium"],
  },
  {
    id: "animal-012",
    productName: "Butter",
    productImage: "/products/agriProducts/DairyAndLivestock/butter.jpg",
    price: "200 EGP/kg",
    discountPrice: "180 EGP/kg",
    rating: 4.6,
    tags: ["Dairy", "Butter", "Natural", "Spread"],
  },
];

////////////////////////////////////////////
////////   cropAndFreshProducesData

export const seedAndSaplingProducts = [
  {
    id: "seed-01",
    productName: "Burpee Sweet Pepper Seeds",
    productImage:
      "/products/agriProducts/SeedsAndSaplings/burpeeSweetPepperSeeds.webp",
    price: "18 EGP/pack",
    discountPrice: "15 EGP/pack",
    rating: 4.6,
    tags: ["Seeds", "Vegetable", "Pepper", "Cultivation"],
  },
  {
    id: "seed-02",
    productName: "Burpee Carrot Seeds",
    productImage:
      "/products/agriProducts/SeedsAndSaplings/burpeeCarrotSeeds.webp",
    price: "12 EGP/pack",
    discountPrice: "10 EGP/pack",
    rating: 4.5,
    tags: ["Seeds", "Vegetable", "Carrot", "Root"],
  },
  {
    id: "seed-03",
    productName: "Burpee Pea Seeds",
    productImage: "/products/agriProducts/SeedsAndSaplings/burpeePeaSeeds.webp",
    price: "20 EGP/pack",
    discountPrice: "17 EGP/pack",
    rating: 4.4,
    tags: ["Seeds", "Vegetable", "Pea", "Legume"],
  },
  {
    id: "seed-04",
    productName: "Burpee Watermelon Seeds",
    productImage:
      "/products/agriProducts/SeedsAndSaplings/burpeeWatermelonSeeds.webp",
    price: "22 EGP/pack",
    discountPrice: "19 EGP/pack",
    rating: 4.8,
    tags: ["Seeds", "Fruit", "Watermelon", "Summer"],
  },
  {
    id: "seed-05",
    productName: "Ferry Morse Tomato Seeds",
    productImage:
      "/products/agriProducts/SeedsAndSaplings/ferryTomatoSeeds.webp",
    price: "14 EGP/pack",
    discountPrice: "12 EGP/pack",
    rating: 4.3,
    tags: ["Seeds", "Vegetable", "Tomato", "Essential"],
  },
  {
    id: "seed-06",
    productName: "Tomato Sow Right Seeds",
    productImage:
      "/products/agriProducts/SeedsAndSaplings/tomatoSowRightSeeds.jpg",
    price: "130 EGP/plant",
    discountPrice: "115 EGP/plant",
    rating: 4.9,
    tags: ["Sapling", "Vegetable", "Tomato", "Starter Plant"],
  },
];
