[
  {
    id: "fruit-01",
    productName: "Organic Gala Apples",
    image: "https://images.openai.com/thumbnails/url/turn0image0",
    shortDescription: "Juicy organic Gala apples – sold per kg.",
    price: "55 EGP/kg",
    discountPrice: "50 EGP/kg",
    rating: 4.7,
    category: "Fruits",
    tags: ["organic", "sweet"],
    stock: 200,
    unit: "kg",
  },
  {
    id: "fruit-02",
    productName: "Organic Fuji Apples",
    image: "https://images.openai.com/thumbnails/url/turn0image1",
    shortDescription: "Crisp Fuji apples, freshly harvested.",
    price: "60 EGP/kg",
    discountPrice: "55 EGP/kg",
    rating: 4.8,
    category: "Fruits",
    tags: ["crisp", "farm-fresh"],
    stock: 150,
    unit: "kg",
  },
  {
    id: "fruit-03",
    productName: "Organic Granny Smith",
    image: "https://images.openai.com/thumbnails/url/turn0image4",
    shortDescription: "Tart Granny Smiths, perfect for baking.",
    price: "58 EGP/kg",
    discountPrice: "53 EGP/kg",
    rating: 4.6,
    category: "Fruits",
    tags: ["tart", "baking"],
    stock: 180,
    unit: "kg",
  },
  {
    id: "fruit-04",
    productName: "Organic Ambrosia Apples",
    image: "https://images.openai.com/thumbnails/url/turn0image3",
    shortDescription: "Sweet and aromatic Ambrosia apples.",
    price: "62 EGP/kg",
    discountPrice: "58 EGP/kg",
    rating: 4.9,
    category: "Fruits",
    tags: ["sweet", "fragrant"],
    stock: 130,
    unit: "kg",
  },
  {
    id: "fruit-05",
    productName: "Organic Medley Mix",
    image: "https://images.openai.com/thumbnails/url/turn0image2",
    shortDescription: "Mixed pack of Organic apples.",
    price: "65 EGP/kg",
    discountPrice: "60 EGP/kg",
    rating: 4.8,
    category: "Fruits",
    tags: ["variety", "mixed"],
    stock: 160,
    unit: "kg",
  },
  {
    id: "fruit-06",
    productName: "Organic Fuji Gift Box",
    image: "https://images.openai.com/thumbnails/url/turn0image1",
    shortDescription: "Premium Fuji sliced gift-box.",
    price: "120 EGP/box",
    discountPrice: "110 EGP/box",
    rating: 4.9,
    category: "Fruits",
    tags: ["gift", "premium"],
    stock: 50,
    unit: "box",
  },
  {
    id: "fruit-07",
    productName: "Organic Gala 2 lb Bag",
    image: "https://images.openai.com/thumbnails/url/turn0image5",
    shortDescription: "2 lb bag of Gala apples.",
    price: "100 EGP/bag",
    discountPrice: "95 EGP/bag",
    rating: 4.7,
    category: "Fruits",
    tags: ["bulk", "bagged"],
    stock: 90,
    unit: "bag",
  },
  {
    id: "fruit-08",
    productName: "Organic Apple Bowl",
    image: "https://images.openai.com/thumbnails/url/turn0image6",
    shortDescription: "Apple bowl mix for gatherings.",
    price: "150 EGP/bowl",
    discountPrice: "140 EGP/bowl",
    rating: 4.8,
    category: "Fruits",
    tags: ["party", "mix"],
    stock: 40,
    unit: "bowl",
  },
];
